title: Hicham Atanane # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2nd Year Data and Knowledge Engineering student at School of Information Science  
  <br><br>
  Looking for a summer internship in machine learning and data science fields 
  <br><br>
  <a href="https://www.linkedin.com/in/hicham-atanane/">View My LinkedIn Profile</a>
  Email: hicham.atanane01@gmail.com
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
